name: necrophilia
description:
  Provides common useless widgets built with macros.
  This package is useless while macros is experimental.
version: 0.0.2

environment:
  sdk: ^3.6.0-146.0.dev
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  macros: ^0.1.2-main.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
